### ISSUE TITLE
1.19.2 arclight 核心上运行时会很卡，以及产生大量报错

### ISSUE THREAD

**Issue by XyRealm** [MrLv0816/ClearEntity#3]
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getSpawnLocation()" because "world" is null
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.nms.NMSUtils.<clinit>(NMSUtils.java:26)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: java.lang.RuntimeException: Cannot setup nmsModule: Cannot invoke "Object.getClass()" because "cn.konfan.clearentity.nms.NMSUtils.nmsEntity" is null
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.nms.NMSUtils.getSaveIDMethodName(NMSUtils.java:140)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.nms.NMSUtils.getSaveID(NMSUtils.java:43)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: java.lang.RuntimeException: Cannot setup nmsModule: Cannot invoke "Object.getClass()" because "cn.konfan.clearentity.nms.NMSUtils.nmsEntity" is null
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.nms.NMSUtils.getSaveIDMethodName(NMSUtils.java:140)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.nms.NMSUtils.getSaveID(NMSUtils.java:43)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: java.lang.RuntimeException: Cannot setup nmsModule: Cannot invoke "Object.getClass()" because "cn.konfan.clearentity.nms.NMSUtils.nmsEntity" is null
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.nms.NMSUtils.getSaveIDMethodName(NMSUtils.java:140)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.nms.NMSUtils.getSaveID(NMSUtils.java:43)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244)
[2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Summer-Tail** [comment]
> [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getSpawnLocation()" because "world" is null [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.nms.NMSUtils.(NMSUtils.java:26) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) [2711��2022 23:01:25.759] [Server thread/ERROR] [STDERR/]: at java.base/java.lang.Thread.run(Thread.java:833) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: java.lang.RuntimeException: Cannot setup nmsModule: Cannot invoke "Object.getClass()" because "cn.konfan.clearentity.nms.NMSUtils.nmsEntity" is null [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.nms.NMSUtils.getSaveIDMethodName(NMSUtils.java:140) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.nms.NMSUtils.getSaveID(NMSUtils.java:43) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) [2711��2022 23:01:25.764] [Server thread/ERROR] [STDERR/]: at java.base/java.lang.Thread.run(Thread.java:833) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: java.lang.RuntimeException: Cannot setup nmsModule: Cannot invoke "Object.getClass()" because "cn.konfan.clearentity.nms.NMSUtils.nmsEntity" is null [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.nms.NMSUtils.getSaveIDMethodName(NMSUtils.java:140) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.nms.NMSUtils.getSaveID(NMSUtils.java:43) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) [2711��2022 23:01:25.765] [Server thread/ERROR] [STDERR/]: at java.base/java.lang.Thread.run(Thread.java:833) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: java.lang.RuntimeException: Cannot setup nmsModule: Cannot invoke "Object.getClass()" because "cn.konfan.clearentity.nms.NMSUtils.nmsEntity" is null [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.nms.NMSUtils.getSaveIDMethodName(NMSUtils.java:140) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.nms.NMSUtils.getSaveID(NMSUtils.java:43) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.Clear.Rules.getRules(Rules.java:29) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$2(EntityClear.java:72) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.lambda$run$3(EntityClear.java:66) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at cn.konfan.clearentity.task.EntityClear.run(EntityClear.java:66) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:82) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/arclight@1.19.2-1.0.1-SNAPSHOT-c8f3f571/org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftSchedulerMixin.java:415) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.handler$zbl000$arclight$runScheduler(MinecraftServerMixin.java:2370) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServerMixin.java) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServerMixin.java:292) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServerMixin.java:806) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2127) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServerMixin.java:244) [2711��2022 23:01:25.767] [Server thread/ERROR] [STDERR/]: at java.base/java.lang.Thread.run(Thread.java:833)


初步判断是因为没有找到末地世界造成的

**Comment by Kotori0629** [comment]
Closed
