### ISSUE TITLE
2.5.9在1.12.2CAT端上一直重复刷报错

### ISSUE THREAD

**Issue by yiliya123** [MrLv0816/ClearEntity#6]
[18:38:25] [Craft Scheduler Thread - 4629/WARN]: [ClearEntity] Plugin ClearEntity v2.5.9 generated an exception while executing task 47
java.lang.RuntimeException: Cannot find Bin.before field in message.yml error:null
        at cn.konfan.clearentity.config.LanguageConfig.getString(LanguageConfig.java:34) ~[?:?]
        at cn.konfan.clearentity.task.BinClearTask.run(BinClearTask.java:23) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-dae70adc]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-dae70adc]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

**Comment by Summer-Tail** [comment]
报错已经写的很明显了，没有在message.yml中找到Bin.before这个节点，综上所述，删除语言文件重新生成即可
